<%@ Page Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="IngrA.aspx.cs" Inherits="WebApplication2.Admin.IngrA" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <form id="form1" >
    <div>
        <asp:Button ID="Insert" runat="server" Text="Insert" onclick="Insert_Click"/>
      
    <asp:gridview ID="Gridview1" runat="server" AllowPaging="True" AllowSorting="True" 
            AutoGenerateColumns="False" AutoGeneratedRows="True"
            BackColor="#DEBA84" BorderColor="#DEBA84" 
            BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2" 
            DataKeyNames="IngredientID" style="margin-left: 0px" 
            DataSourceID="LinqDataSource1" 
              >
        <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
        <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
        <Columns>
            <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" />
            <asp:BoundField DataField="IngredientID" HeaderText="IngredientID" 
                ReadOnly="True" SortExpression="IngredientID" InsertVisible="False" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Ambalaj" HeaderText="Ambalaj" 
                SortExpression="Ambalaj" />
            <asp:BoundField DataField="UnitPrice" HeaderText="UnitPrice" 
                SortExpression="UnitPrice" />
            <asp:BoundField DataField="Incompatibilities" HeaderText="Incompatibilities" 
                SortExpression="Incompatibilities" />
        </Columns>
        <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="Black" />
        </asp:gridview>
        <asp:LinqDataSource ID="LinqDataSource1" runat="server" 
            ContextTypeName="WebApplication2.App_DB.ProductDataContext" 
            TableName="Ingredients" EnableUpdate="True" 
            OrderBy="IngredientID desc, Name desc" EnableDelete="True" 
            >
        </asp:LinqDataSource>
           </div>
    </form>
</asp:Content>
